### ISSUE TITLE
Remove `replace` of `machine-controller-manager` dependency

### ISSUE THREAD

**Issue by afritzler** [ironcore-dev/machine-controller-manager-provider-ironcore#65]
# Summary

Currently we are using a `replace` dependency of the MCM (https://github.com/onmetal/machine-controller-manager-provider-onmetal/blob/main/go.mod#L30). This should be changed and we should switch to the upstream version.

**Comment by sujeet01** [comment]
@afritzler Upstream version of `gardener/machine-controller-manager@v0.47.1` is currently using older `k8s.io/*` package versions `v0.22.9`. But we're using version `v0.26.1` for all of our `k8s.io/*` packages.

**Comment by afritzler** [comment]
No we can't down grade our k8s deps as we rely on the newest version. Ok then lets put this one on hold until the machine controller manager is bumped to the latest version.

**Comment by afritzler** [comment]
Waiting for https://github.com/gardener/machine-controller-manager/pull/792 to get merged.
